const $=s=>document.querySelector(s);
const canvas=$("#chart"),ctx=canvas.getContext("2d");
let price=104218, points=Array.from({length:55},(_,i)=>price*(1+(Math.sin(i/5)*.008)+(Math.random()-.5)*.006));
function draw(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;ctx.clearRect(0,0,w,h);const min=Math.min(...points),max=Math.max(...points),range=max-min||1;ctx.beginPath();points.forEach((v,i)=>{const x=i*(w/(points.length-1)),y=h-20-((v-min)/range)*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineWidth=2;ctx.strokeStyle="#9b8cff";ctx.stroke();const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#8b7cff22");g.addColorStop(1,"#8b7cff00");ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();ctx.fillStyle=g;ctx.fill()}
function render(){const p=price.toLocaleString("en-US",{style:"currency",currency:"USD"});$("#price").textContent=p;$("#heroPrice").textContent=p;$("#high").textContent=(price*1.0148).toLocaleString("en-US",{style:"currency",currency:"USD"});$("#low").textContent=(price*.977).toLocaleString("en-US",{style:"currency",currency:"USD"});draw()}
function event(label,msg){const row=document.createElement("div");row.innerHTML="<b>"+label+"</b><span>"+msg+"</span><time>Now</time>";$("#events").prepend(row)}
$("#analyzeBtn").onclick=()=>{const b=$("#analyzeBtn");b.disabled=true;b.textContent="Analyzing…";setTimeout(()=>{const actions=["HOLD","HOLD","BUY"];const a=actions[Math.floor(Math.random()*actions.length)];const c=a==="BUY"?68+Math.floor(Math.random()*20):70+Math.floor(Math.random()*18);$("#decision").textContent=a;$("#decision").className="decision "+a.toLowerCase();$("#confidence").textContent=c+"%";$("#confidenceBar").style.width=c+"%";$("#reason").textContent=a==="BUY"?"Momentum is positive, but the execution layer still applies position and risk limits.":"Signals are mixed, so the conservative engine is waiting for stronger evidence.";event("AI",a+" decision generated");b.disabled=false;b.textContent="Run market analysis";},900)};
$("#paperBtn").onclick=()=>{alert("Paper trading stays enabled in this website. Live execution must be controlled securely on the backend.")};
$("#themeBtn").onclick=()=>document.body.classList.toggle("light");
$("#pair").onchange=e=>{const v=e.target.value.split("/")[0];event("PAIR",v+"/USDT selected")};
window.addEventListener("resize",draw);render();setInterval(()=>{price*=1+(Math.random()-.5)*.0008;points.shift();points.push(price);render()},3500);