const SUPABASE_URL="https://vihbsfrwnslnmheowkhy.supabase.co";
const SUPABASE_KEY="sb_publishable_HIMGxb-O6fj9O7OzT4ukuQ_jm5W8mWz";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);
const canvas=$("#chart"),ctx=canvas.getContext("2d");
let user=null,price=0,points=[],syncChannel=null,marketTimer=null;

function draw(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;ctx.clearRect(0,0,w,h);if(points.length<2)return;const min=Math.min(...points),max=Math.max(...points),range=max-min||1;ctx.beginPath();points.forEach((v,i)=>{const x=i*(w/(points.length-1)),y=h-18-((v-min)/range)*(h-36);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineWidth=2;ctx.strokeStyle="#9b8cff";ctx.stroke()}
function money(v){return Number(v||0).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2})}
function pairName(v){return String(v).replace("USDT","/USDT")}
function render(){const p=money(price);$("#price").textContent=p;$("#heroPrice").textContent=p;draw()}
function event(label,msg){const row=document.createElement("div");row.innerHTML="<b>"+label+"</b><span>"+String(msg).replace(/[<>]/g,"")+"</span><time>Now</time>";$("#events").prepend(row);while($("#events").children.length>15)$("#events").lastElementChild.remove()}
function setDecision(a,c,reason){a=String(a||"HOLD").toUpperCase();$("#decision").textContent=a;$("#decision").className="decision "+a.toLowerCase();$("#confidence").textContent=Math.round(Number(c)||0)+"%";$("#confidenceBar").style.width=Math.max(0,Math.min(100,Number(c)||0))+"%";$("#reason").textContent=reason||"No reason provided."}
function setConnected(v){$("#connectionStatus").innerHTML="<i></i> "+(v?"Synced":"Offline")}
function subscribeSync(){if(!user||syncChannel)return;syncChannel=sb.channel("trading-web-sync-"+user.id).on("postgres_changes",{event:"*",schema:"public",table:"trading_bot_settings",filter:"user_id=eq."+user.id},loadSettings).on("postgres_changes",{event:"*",schema:"public",table:"trading_bot_status",filter:"user_id=eq."+user.id},loadStatus).subscribe()}
async function loadWallet(){if(!user)return;$("#walletCard").classList.remove("hidden");const {data,error}=await sb.from("wallet_accounts").select("available_balance,locked_balance,provider").eq("user_id",user.id).maybeSingle();if(error){$("#walletNotice").textContent="Wallet sync is unavailable right now.";return}if(data){$("#walletBalance").textContent=new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(Number(data.available_balance||0));$("#walletLocked").textContent=new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(Number(data.locked_balance||0));$("#walletProvider").textContent=(data.provider||"Provider")+" · Connected"}}
function showUser(u){user=u;document.body.classList.toggle("authenticated",!!u);if(u){$("#authCard").classList.add("hidden");$("#userBar").classList.remove("hidden");$("#userEmail").textContent=u.email||"Connected";setConnected(true);subscribeSync()}else{$("#authCard").classList.remove("hidden");$("#userBar").classList.add("hidden");setConnected(false);if(syncChannel){sb.removeChannel(syncChannel);syncChannel=null}}}
async function loadSettings(){if(!user)return;const {data,error}=await sb.from("trading_bot_settings").select("*").eq("user_id",user.id).maybeSingle();if(error){event("SYNC","Settings read failed");return}if(data){$("#settingsPair").value=data.symbol;$("#pair").value=data.symbol;$("#positionLimit").value=data.position_limit_usdt;$("#stopLoss").value=data.stop_loss_pct;$("#takeProfit").value=data.take_profit_pct;$("#paperMode").checked=data.paper_mode;event("SYNC","Settings synchronized")}}
async function saveSettings(notify=true){if(!user){$("#authMessage").textContent="Sign in first.";return}const payload={user_id:user.id,symbol:$("#settingsPair").value,position_limit_usdt:Math.max(.1,Number($("#positionLimit").value)||5),stop_loss_pct:Math.max(.1,Number($("#stopLoss").value)||2),take_profit_pct:Math.max(.1,Number($("#takeProfit").value)||3),paper_mode:$("#paperMode").checked,updated_at:new Date().toISOString()};const {error}=await sb.from("trading_bot_settings").upsert(payload,{onConflict:"user_id"});if(error){$("#authMessage").textContent=error.message;return}$("#pair").value=payload.symbol;event("SYNC","Settings saved for Android + Web");if(notify){$("#saveSettings").textContent="Saved ✓";setTimeout(()=>$("#saveSettings").textContent="Save & sync with app",1200)}}
async function loadStatus(){if(!user)return;const {data}=await sb.from("trading_bot_status").select("*").eq("user_id",user.id).maybeSingle();if(!data)return;$("#botState").textContent=data.mode||"PAPER";$("#botStateDetail").textContent=data.state||"WAITING";const n=pairName(data.symbol||"BTCUSDT");$("#chartPair").textContent=n;$("#metricPair")?.textContent=n;if(data.price){price=Number(data.price);points.push(price);if(points.length>80)points.shift();render()}setDecision(data.action,Number(data.confidence),data.reason||"No reason provided.");$("#updated").textContent="Synced "+new Date(data.updated_at||Date.now()).toLocaleTimeString();$("#heroUpdated").textContent="Bot sync "+new Date(data.updated_at||Date.now()).toLocaleTimeString();event("BOT",(data.action||"HOLD")+" · "+(data.state||"WAITING"))}
async function loadMarket(){const symbol=$("#pair").value==="BTCUSDT"?"BTC-USD":$("#pair").value==="ETHUSDT"?"ETH-USD":"SOL-USD";try{const r=await fetch("https://api.exchange.coinbase.com/products/"+symbol+"/ticker");if(!r.ok)throw new Error("Market feed unavailable");const j=await r.json();const next=Number(j.price);if(!Number.isFinite(next))return;price=next;points.push(next);if(points.length>80)points.shift();$("#high").textContent=money(Number(j.price)*1.012);$("#low").textContent=money(Number(j.price)*.988);$("#change").textContent="Live market feed";$("#heroUpdated").textContent="Updated "+new Date().toLocaleTimeString();render()}catch(e){$("#change").textContent="Feed unavailable"}}
async function runAnalysis(){if(!user){alert("Sign in first.");return}const b=$("#analyzeBtn");b.disabled=true;b.textContent="Analyzing…";try{const session=(await sb.auth.getSession()).data.session;const r=await fetch(SUPABASE_URL+"/functions/v1/trading-analysis",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+(session?.access_token||"")},body:JSON.stringify({symbol:$("#pair").value})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Analysis failed");let raw=j.decision||"";try{raw=JSON.parse(raw)}catch{}if(typeof raw==="object"){setDecision(raw.action,Number(raw.confidence),raw.reason);if($("#terminalSignal")){$("#terminalSignal").textContent=String(raw.action||"HOLD").toUpperCase();$("#terminalSignal").className="ai-signal "+String(raw.action||"HOLD").toLowerCase()}if($("#terminalReason"))$("#terminalReason").textContent=raw.reason||"AI analysis complete."}event("AI","Latest analysis received")}catch(e){event("AI","Analysis unavailable: "+e.message)}finally{b.disabled=false;b.textContent="Run AI analysis"}}
$("#signInBtn").onclick=async()=>{const email=$("#email").value.trim(),password=$("#password").value;$("#authMessage").textContent="Signing in…";const {error}=await sb.auth.signInWithPassword({email,password});$("#authMessage").textContent=error?error.message:"Signed in."}
$("#signUpBtn").onclick=async()=>{const email=$("#email").value.trim(),password=$("#password").value;if(password.length<6){$("#authMessage").textContent="Use at least 6 characters.";return}$("#authMessage").textContent="Creating account…";const {error}=await sb.auth.signUp({email,password});$("#authMessage").textContent=error?error.message:"Account created. Check email if confirmation is enabled."}
$("#signOutBtn").onclick=()=>sb.auth.signOut();$("#saveSettings").onclick=()=>saveSettings(true);
$("#paperBtn").onclick=()=>{if(!user){alert("Sign in first.");return}$("#paperMode").checked=true;saveSettings(true)};
$("#analyzeBtn").onclick=runAnalysis;
$("#pair").onchange=e=>{const v=e.target.value;$("#settingsPair").value=v;$("#chartPair").textContent=pairName(v);event("PAIR",v+" selected");loadMarket();if(user)saveSettings(false)};
$("#themeBtn").onclick=()=>document.body.classList.toggle("light");$("#clearEvents").onclick=()=>{$("#events").innerHTML=""};
$("#depositBtn").onclick=()=>event("WALLET","Deposit will be enabled after the wallet provider is connected");
$("#withdrawBtn").onclick=()=>event("WALLET","Withdrawal requires provider verification and KYC");
sb.auth.onAuthStateChange(async(_event,session)=>{showUser(session?.user||null);if(session?.user){await loadSettings();await loadStatus();await loadWallet()}});
(async()=>{const {data}=await sb.auth.getSession();showUser(data.session?.user||null);await loadMarket();if(data.session?.user){await loadSettings();await loadStatus();await loadWallet()}marketTimer=setInterval(loadMarket,30000)})();
window.addEventListener("resize",draw);

let terminalSide="BUY";function drawTerminal(){const c=$("#terminalChart"),ctx=c?.getContext("2d");if(!c||!ctx)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;if(points.length<2)return;const min=Math.min(...points),max=Math.max(...points),range=max-min||1;ctx.clearRect(0,0,w,h);ctx.strokeStyle="#20262d";ctx.lineWidth=1;for(let n=1;n<6;n++){ctx.beginPath();ctx.moveTo(0,n*h/6);ctx.lineTo(w,n*h/6);ctx.stroke()}ctx.strokeStyle="#f0b90b";ctx.lineWidth=2;ctx.beginPath();points.forEach((v,n)=>{const x=n*w/(points.length-1),y=h-15-(v-min)/range*(h-30);n?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
async function terminalBook(){try{const p=$("#terminalPairSelect").value==="BTCUSDT"?"BTC-USD":$("#terminalPairSelect").value==="ETHUSDT"?"ETH-USD":"SOL-USD";const r=await fetch("https://api.exchange.coinbase.com/products/"+p+"/book?level=2");const j=await r.json();const row=(x,cl)=>"<div class='bookrow "+cl+"'><span>"+Number(x[0]).toFixed(2)+"</span><span>"+Number(x[1]).toFixed(5)+"</span><span>"+(Number(x[0])*Number(x[1])).toFixed(2)+"</span></div>";$("#terminalAsks").innerHTML=(j.asks||[]).slice(-7).reverse().map(x=>row(x,"askrow")).join("");$("#terminalBids").innerHTML=(j.bids||[]).slice(0,7).map(x=>row(x,"bidrow")).join("");$("#terminalMid").textContent=price?money(price):"—"}catch(e){}}
const oldRender=render;render=function(){oldRender();if($("#tPrice")){$("#tPrice").textContent=money(price);$("#tHigh").textContent=money(price*1.012);$("#tLow").textContent=money(price*.988);$("#terminalPair").textContent=pairName($("#terminalPairSelect")?.value||"BTCUSDT");const a=Number($("#terminalAmount")?.value)||0;$("#terminalTotal").textContent=money(a*price);drawTerminal()}};
$("#terminalPairSelect").onchange=()=>{if($("#pair"))$("#pair").value=$("#terminalPairSelect").value;points=[];loadMarket();terminalBook()};$("#terminalAmount").oninput=render;$("#terminalBuy").onclick=()=>{terminalSide="BUY";$("#terminalBuy").classList.add("active");$("#terminalSell").classList.remove("active");$("#terminalOrder").textContent="Buy "+($("#terminalPairSelect").value||"BTCUSDT").replace("USDT","")};$("#terminalSell").onclick=()=>{terminalSide="SELL";$("#terminalSell").classList.add("active");$("#terminalBuy").classList.remove("active");$("#terminalOrder").textContent="Sell "+($("#terminalPairSelect").value||"BTCUSDT").replace("USDT","")};$("#terminalOrder").onclick=()=>{if(!user){alert("Sign in first.");return}event("PAPER",terminalSide+" order simulated");alert("Paper order recorded. Live execution is disabled.");};$("#terminalAnalyze").onclick=runAnalysis;setInterval(()=>{if(user)terminalBook()},15000);window.addEventListener("resize",drawTerminal);
