const SUPABASE_URL="https://vihbsfrwnslnmheowkhy.supabase.co";
const SUPABASE_KEY="sb_publishable_HIMGxb-O6fj9O7OzT4ukuQ_jm5W8mWz";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);
const canvas=$("#chart"),ctx=canvas.getContext("2d");
let user=null,price=104218,points=Array.from({length:55},()=>price*(1+(Math.random()-.5)*.012));

function draw(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height,min=Math.min(...points),max=Math.max(...points),range=max-min||1;ctx.clearRect(0,0,w,h);ctx.beginPath();points.forEach((v,i)=>{const x=i*(w/(points.length-1)),y=h-20-((v-min)/range)*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineWidth=2;ctx.strokeStyle="#9b8cff";ctx.stroke()}
function money(v){return Number(v||0).toLocaleString("en-US",{style:"currency",currency:"USD"})}
function render(){const p=money(price);$("#price").textContent=p;$("#heroPrice").textContent=p;$("#high").textContent=money(price*1.0148);$("#low").textContent=money(price*.977);draw()}
function event(label,msg){const row=document.createElement("div");row.innerHTML="<b>"+label+"</b><span>"+msg+"</span><time>Now</time>";$("#events").prepend(row)}
function setDecision(a,c,reason){$("#decision").textContent=a;$("#decision").className="decision "+a.toLowerCase();$("#confidence").textContent=Math.round(c)+"%";$("#confidenceBar").style.width=Math.max(0,Math.min(100,c))+"%";$("#reason").textContent=reason}
function setConnected(v){$("#connectionStatus").innerHTML="<i></i> "+(v?"Synced":"Offline");}
let syncChannel=null;
function subscribeSync(){if(!user||syncChannel)return;syncChannel=sb.channel("trading-web-sync-"+user.id).on("postgres_changes",{event:"*",schema:"public",table:"trading_bot_settings",filter:"user_id=eq."+user.id},()=>loadSettings()).on("postgres_changes",{event:"*",schema:"public",table:"trading_bot_status",filter:"user_id=eq."+user.id},()=>loadStatus()).subscribe()}
function showUser(u){user=u;if(u){$("#authCard").classList.add("hidden");$("#userBar").classList.remove("hidden");$("#userEmail").textContent=u.email||"Connected";setConnected(true);subscribeSync()}else{$("#authCard").classList.remove("hidden");$("#userBar").classList.add("hidden");setConnected(false);if(syncChannel){sb.removeChannel(syncChannel);syncChannel=null}}}

async function loadSettings(){if(!user)return;const {data,error}=await sb.from("trading_bot_settings").select("*").eq("user_id",user.id).maybeSingle();if(error){event("SYNC","Settings read failed");return}if(data){$("#settingsPair").value=data.symbol;$("#pair").value=data.symbol;$("#positionLimit").value=data.position_limit_usdt;$("#stopLoss").value=data.stop_loss_pct;$("#takeProfit").value=data.take_profit_pct;$("#paperMode").checked=data.paper_mode;event("SYNC","Settings loaded from your account")}else{await saveSettings(false)}}
async function saveSettings(notify=true){if(!user){$("#authMessage").textContent="Sign in first.";return}const payload={user_id:user.id,symbol:$("#settingsPair").value,position_limit_usdt:Number($("#positionLimit").value),stop_loss_pct:Number($("#stopLoss").value),take_profit_pct:Number($("#takeProfit").value),paper_mode:$("#paperMode").checked,updated_at:new Date().toISOString()};const {error}=await sb.from("trading_bot_settings").upsert(payload,{onConflict:"user_id"});if(error){$("#authMessage").textContent=error.message;return}$("#pair").value=payload.symbol;event("SYNC","Settings saved and available to the Android app");if(notify)$("#saveSettings").textContent="Saved ✓";setTimeout(()=>$("#saveSettings").textContent="Save & sync with app",1200)}
async function loadStatus(){if(!user)return;const {data}=await sb.from("trading_bot_status").select("*").eq("user_id",user.id).maybeSingle();if(data){$("#botState").textContent=data.mode;$("#botStateDetail").textContent=data.state;$("#metricPair").textContent=data.symbol.replace("USDT","/USDT");$("#chartPair").textContent=data.symbol.replace("USDT","/USDT");if(data.price){price=Number(data.price);render()}setDecision(data.action,Number(data.confidence),data.reason||"No reason provided.");$("#updated").textContent="Synced "+new Date(data.updated_at).toLocaleTimeString();event("BOT",data.action+" · "+data.state)}} 

$("#signInBtn").onclick=async()=>{const email=$("#email").value.trim(),password=$("#password").value;$("#authMessage").textContent="Signing in…";const {error}=await sb.auth.signInWithPassword({email,password});$("#authMessage").textContent=error?error.message:"Signed in."}
$("#signUpBtn").onclick=async()=>{const email=$("#email").value.trim(),password=$("#password").value;if(password.length<6){$("#authMessage").textContent="Use at least 6 characters.";return}$("#authMessage").textContent="Creating account…";const {error}=await sb.auth.signUp({email,password});$("#authMessage").textContent=error?error.message:"Account created. Check your email if confirmation is enabled."}
$("#signOutBtn").onclick=()=>sb.auth.signOut();
$("#saveSettings").onclick=()=>saveSettings(true);
$("#paperBtn").onclick=()=>{if(!user){alert("Sign in first to sync this setting with the app.");return}$("#paperMode").checked=true;saveSettings(true)};
$("#analyzeBtn").onclick=async()=>{if(!user){alert("Sign in first.");return}const b=$("#analyzeBtn");b.disabled=true;b.textContent="Analyzing…";try{const r=await fetch("https://vihbsfrwnslnmheowkhy.supabase.co/functions/v1/trading-bot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:$("#pair").value})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Analysis failed");let raw=j.decision||"";try{raw=JSON.parse(raw)}catch{}if(typeof raw==="object")setDecision(raw.action||"HOLD",Number(raw.confidence||0),raw.reason||"Analysis returned no reason.");event("AI","Latest analysis received")}catch(e){event("AI","Analysis unavailable: "+e.message)}finally{b.disabled=false;b.textContent="Run market analysis"}};
$("#pair").onchange=e=>{const v=e.target.value;$("#settingsPair").value=v;$("#metricPair").textContent=v.replace("USDT","/USDT");$("#chartPair").textContent=v.replace("USDT","/USDT");$("#heroPair").textContent=v.replace("USDT","/USDT");event("PAIR",v+" selected");if(user)saveSettings(false)};
$("#themeBtn").onclick=()=>document.body.classList.toggle("light");
sb.auth.onAuthStateChange(async(_event,session)=>{showUser(session?.user||null);if(session?.user){await loadSettings();await loadStatus()}});
(async()=>{const {data}=await sb.auth.getSession();showUser(data.session?.user||null);if(data.session?.user){await loadSettings();await loadStatus()}else{render()}})();
user&&
